# eth node rpc request
[rpc]
# it is better to launch your own ETH node!
# go to infura to register your account is also acceptable
url = "https://mainnet.infura.io/v3/"
timeout = 30

[gas]
# it is better to register your account at ethgasstation
gas_level = "fast"
eth_gas_url = "https://ethgasstation.info/json/ethgasAPI.json"

# accounts for keeper transaction
[[accounts]]
address = ""
private_key = ""

[contracts]
perpetual = "0x220a9f0DD581cbc58fcFb907De0454cBF3777f76"
collateral_token = "0x0000000000000000000000000000000000000000"

[mcdex]
market_id = "rqbap"
url = "https://mcdex.io/api"
position_limit = 1000
leverage = 5
inverse = true

[logging]
version = 1
disable_existing_loggers = true
[logging.formatters]
    [logging.formatters.simple]
    format= '%(asctime)s %(levelname)-7s - %(message)s - [%(filename)s:%(lineno)d:%(funcName)s]'

[logging.handlers]
    [logging.handlers.console]
    class = "logging.StreamHandler"
    level = "INFO"
    formatter = 'simple'
    stream = "ext://sys.stdout"
    [logging.handlers.file_handler]
    class = "logging.handlers.RotatingFileHandler"
    level = "DEBUG"
    formatter = 'simple'
    filename = "./log/keeper.log"
    maxBytes = 104857600 # 100MB
    backupCount = 2
    encoding = "utf8"
[logging.root]
level= "DEBUG"
handlers= ["console", "file_handler"]
